"""Orchestrator MCP server - FastMCP protocol layer.

Exposes cross-agent workflow planning and execution gating tools.

Run via stdio:
    python servers/orchestrator/mcp_server.py
"""

from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from typing import Annotated

from fastmcp import FastMCP
from pydantic import Field

from shared.errors import AdsMcpError
from shared.models import ToolRequest
from tools.workflow import plan_cross_agent_workflow, execute_cross_agent_workflow
from tools.workflow_runs import (
    start_workflow_run,
    get_workflow_run,
    retry_workflow_step,
    cancel_workflow_run,
)

mcp = FastMCP(
    name="orchestrator",
    instructions=(
        "Cross-agent workflow planning tools for ads-mcp. "
        "Always run plan_cross_agent_workflow first, review steps, and only then "
        "execute with dry_run=false and explicit approval_id."
    ),
)


def _error_response(exc: Exception, tool: str) -> dict:
    if isinstance(exc, AdsMcpError):
        return exc.to_response(service="orchestrator", request_id=None)
    return AdsMcpError(
        status_code=500,
        error_code="INTERNAL_ERROR",
        message="Unhandled orchestrator tool error.",
        tool=tool,
        details={"reason": str(exc)},
    ).to_response(service="orchestrator", request_id=None)


@mcp.tool()
def orchestrator_plan_cross_agent_workflow(
    business_key: Annotated[str, Field(description="Business key, e.g. 'rnr-electrician' or 'gq-painting'")],
    objective: Annotated[str, Field(description="High-level orchestration objective")] = "Cross-agent optimization workflow",
    services: Annotated[list[str] | None, Field(description="Optional subset of services to include")]=None,
    mcp_base_url: Annotated[str, Field(description="Base URL for routed service endpoints")] = "https://mcp.rctechbridge.com",
) -> dict:
    """Generate a dry-run cross-agent workflow plan with ordered service steps."""
    request = ToolRequest(
        businessKey=business_key,
        dryRun=True,
        payload={"objective": objective, "services": services or []},
        requestMeta={"mcpBaseUrl": mcp_base_url},
    )
    try:
        return plan_cross_agent_workflow(request, request_id=None)
    except Exception as exc:
        return _error_response(exc, "orchestrator_plan_cross_agent_workflow")


@mcp.tool()
def orchestrator_execute_cross_agent_workflow(
    business_key: Annotated[str, Field(description="Business key, e.g. 'rnr-electrician' or 'gq-painting'")],
    approval_id: Annotated[str, Field(description="Approval ID from dry-run response")],
    objective: Annotated[str, Field(description="High-level orchestration objective")] = "Cross-agent optimization workflow",
    services: Annotated[list[str] | None, Field(description="Optional subset of services to include")]=None,
) -> dict:
    """Queue a validated workflow execution request after explicit approval."""
    request = ToolRequest(
        businessKey=business_key,
        dryRun=False,
        approvalId=approval_id,
        payload={"objective": objective, "services": services or []},
    )
    try:
        return execute_cross_agent_workflow(request, request_id=None)
    except Exception as exc:
        return _error_response(exc, "orchestrator_execute_cross_agent_workflow")


# ── Workflow Run lifecycle tools ──────────────────────────────────────────────

@mcp.tool()
def orchestrator_start_workflow_run(
    business_key: Annotated[str, Field(description="Business key, e.g. 'rnr-electrician'")],
    approval_id: Annotated[str, Field(description="Approval ID authorising this run")],
    run_id: Annotated[str, Field(description="UUID generated by backend-rc for idempotency")],
    objective: Annotated[str, Field(description="Human-readable goal for this run")] = "Cross-agent workflow run",
    steps: Annotated[list[dict] | None, Field(description="Ordered steps [{service, tool_name, payload}]")] = None,
) -> dict:
    """Accept and validate a workflow run queued by backend-rc."""
    request = ToolRequest(
        businessKey=business_key,
        dryRun=False,
        approvalId=approval_id,
        payload={"run_id": run_id, "objective": objective, "steps": steps or []},
    )
    try:
        return start_workflow_run(request, request_id=None)
    except Exception as exc:
        return _error_response(exc, "orchestrator_start_workflow_run")


@mcp.tool()
def orchestrator_get_workflow_run(
    business_key: Annotated[str, Field(description="Business key")],
    run_id: Annotated[str, Field(description="Workflow run UUID")],
    run_status: Annotated[str, Field(description="Current run status from backend DB")] = "unknown",
    steps: Annotated[list[dict] | None, Field(description="Current step list from backend DB")] = None,
) -> dict:
    """Return a status snapshot and progress summary for a workflow run."""
    request = ToolRequest(
        businessKey=business_key,
        dryRun=None,
        payload={"run_id": run_id, "run_status": run_status, "steps": steps or []},
    )
    try:
        return get_workflow_run(request, request_id=None)
    except Exception as exc:
        return _error_response(exc, "orchestrator_get_workflow_run")


@mcp.tool()
def orchestrator_retry_workflow_step(
    business_key: Annotated[str, Field(description="Business key")],
    run_id: Annotated[str, Field(description="Workflow run UUID")],
    step_id: Annotated[str, Field(description="Step UUID to retry")],
    reason: Annotated[str, Field(description="Optional reason for the retry")] = "",
) -> dict:
    """Mark a failed workflow step as eligible for retry."""
    request = ToolRequest(
        businessKey=business_key,
        dryRun=False,
        payload={"run_id": run_id, "step_id": step_id, "reason": reason},
    )
    try:
        return retry_workflow_step(request, request_id=None)
    except Exception as exc:
        return _error_response(exc, "orchestrator_retry_workflow_step")


@mcp.tool()
def orchestrator_cancel_workflow_run(
    business_key: Annotated[str, Field(description="Business key")],
    run_id: Annotated[str, Field(description="Workflow run UUID to cancel")],
    reason: Annotated[str, Field(description="Optional cancellation reason")] = "",
) -> dict:
    """Request cancellation of a queued or running workflow run."""
    request = ToolRequest(
        businessKey=business_key,
        dryRun=False,
        payload={"run_id": run_id, "reason": reason},
    )
    try:
        return cancel_workflow_run(request, request_id=None)
    except Exception as exc:
        return _error_response(exc, "orchestrator_cancel_workflow_run")


if __name__ == "__main__":
    mcp.run()
