"""
Knowledge base query tool for the Google Ads agent.

Reads markdown files from servers/google-ads/knowledge/ and returns
matching tactics summaries based on a topic keyword search.

Knowledge files are generated by scripts/ingest_video.py.
"""
from __future__ import annotations

from pathlib import Path

KNOWLEDGE_DIR = Path(__file__).resolve().parents[1] / "knowledge"

# Sections we return to the agent (avoids sending full transcripts = fewer tokens)
_INCLUDE_HEADERS = {"## topics", "## key tactics", "## summary"}


def _parse_knowledge_file(path: Path) -> dict:
    """Parse a knowledge markdown file into structured fields."""
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()

    # Extract YAML-like frontmatter
    frontmatter: dict = {}
    body_start = 0
    if lines and lines[0].strip() == "---":
        end = next((i for i, l in enumerate(lines[1:], 1) if l.strip() == "---"), None)
        if end:
            for line in lines[1:end]:
                if ":" in line:
                    key, _, val = line.partition(":")
                    frontmatter[key.strip()] = val.strip()
            body_start = end + 1

    body_lines = lines[body_start:]

    # Extract tactic sections only (skip full transcript)
    tactic_sections: list[str] = []
    current_section: list[str] = []
    current_header = ""
    in_transcript = False

    for line in body_lines:
        if line.startswith("## "):
            header = line.strip().lower()
            if header == "## full transcript":
                in_transcript = True
                if current_section:
                    tactic_sections.append("\n".join(current_section).strip())
                current_section = []
                continue
            if in_transcript:
                continue
            if current_section and current_header in _INCLUDE_HEADERS:
                tactic_sections.append("\n".join(current_section).strip())
            current_section = [line]
            current_header = header
            in_transcript = False
        elif not in_transcript:
            current_section.append(line)

    if current_section and current_header in _INCLUDE_HEADERS:
        tactic_sections.append("\n".join(current_section).strip())

    return {
        "file": path.name,
        "source": frontmatter.get("source", ""),
        "date": frontmatter.get("date", ""),
        "topics": frontmatter.get("topics", ""),
        "title": frontmatter.get("title", path.stem),
        "content": "\n\n".join(tactic_sections),
    }


def query_ads_knowledge(topic: str) -> dict:
    """
    Search the Google Ads knowledge base for tactics related to a topic.

    Args:
        topic: Search term, e.g. 'smart bidding', 'quality score', 'keywords', 'budget'

    Returns:
        Dict with matches list and total count. Each match contains:
            title, source, date, topics, content (Key Tactics + Summary only).
    """
    if not KNOWLEDGE_DIR.exists():
        return {
            "status": "ok",
            "query": topic,
            "total": 0,
            "matches": [],
            "note": "No knowledge base yet. Run: python scripts/ingest_video.py <url>",
        }

    md_files = sorted(KNOWLEDGE_DIR.glob("*.md"), key=lambda p: p.stat().st_mtime, reverse=True)
    if not md_files:
        return {
            "status": "ok",
            "query": topic,
            "total": 0,
            "matches": [],
            "note": "Knowledge base is empty. Run: python scripts/ingest_video.py <url>",
        }

    query_terms = topic.lower().split()
    matches: list[dict] = []

    for path in md_files:
        try:
            record = _parse_knowledge_file(path)
        except Exception:
            continue

        searchable = (
            record["title"].lower()
            + " "
            + record["topics"].lower()
            + " "
            + record["content"].lower()
        )

        if any(term in searchable for term in query_terms):
            matches.append(
                {
                    "title": record["title"],
                    "source": record["source"],
                    "date": record["date"],
                    "topics": record["topics"],
                    "content": record["content"],
                }
            )

    if not matches:
        # Return all files if no topic match — let the agent decide
        return {
            "status": "ok",
            "query": topic,
            "total": 0,
            "matches": [],
            "all_topics": [
                {"title": _parse_knowledge_file(p)["title"], "topics": _parse_knowledge_file(p)["topics"]}
                for p in md_files[:20]
            ],
            "note": f"No knowledge files matched '{topic}'. See all_topics for available content.",
        }

    return {
        "status": "ok",
        "query": topic,
        "total": len(matches),
        "matches": matches,
    }
